database:
  path: weather_data.db
plotting:
  ascii_symbols:
  - ─
  - ┄
  - ┅
  - ┈
  - ┉
  default_colors:
  - '#1f77b4'
  - '#ff7f0e'
  - '#2ca02c'
  - '#d62728'
  - '#9467bd'
  dpi: 100
  figure_size:
  - 10
  - 6
region_colors:
  becej: '#e377c2'
  belgrade: '#1f77b4'
  cackak: '#7f7f7f'
  indjija: '#17becf'
  kikinda: '#9467bd'
  kragujevac: '#d62728'
  kraljevo: '#bcbd22'
  leskovac: '#a6cee3'
  new_region: '#ccc03d'
  nis: '#2ca02c'
  novi_pazar: '#17becf'
  novi_sad: '#ff7f0e'
  panchevo: '#e377c2'
  pozarevac: '#fdbf6f'
  sabac: '#ff9896'
  smederevo: '#cab2d6'
  sremska_mitrovica: '#8c564b'
  sremski_karlovci: '#bcbd22'
  subotica: '#9467bd'
  test_region: '#7dcc3d'
  valjevo: '#d62728'
  vranje: '#fb9a99'
  vrbas: '#7f7f7f'
  zrenjanin: '#8c564b'
region_presets:
  central-serbia:
  - kragujevac
  - cackak
  - kraljevo
  - pozarevac
  - smederevo
  major-cities:
  - belgrade
  - novi_sad
  - nis
  - kragujevac
  northern-serbia:
  - belgrade
  - novi_sad
  - subotica
  - zrenjanin
  - panchevo
  southern-serbia:
  - nis
  - leskovac
  - vranje
  - novi_pazar
regions:
  becej:
    latitude: 45.62
    longitude: 20.04
    name: Bečej
  belgrade:
    latitude: 44.79
    longitude: 20.45
    name: Belgrade
  cackak:
    latitude: 43.89
    longitude: 20.35
    name: Čačak
  indjija:
    latitude: 45.05
    longitude: 20.08
    name: Inđija
  kikinda:
    latitude: 45.83
    longitude: 20.47
    name: Kikinda
  kragujevac:
    latitude: 44.02
    longitude: 20.92
    name: Kragujevac
  kraljevo:
    latitude: 43.73
    longitude: 20.69
    name: Kraljevo
  leskovac:
    latitude: 42.99
    longitude: 21.95
    name: Leskovac
  nis:
    latitude: 43.32
    longitude: 21.9
    name: Niš
  novi_pazar:
    latitude: 43.14
    longitude: 20.52
    name: Novi Pazar
  novi_sad:
    latitude: 45.25
    longitude: 19.85
    name: Novi Sad
  panchevo:
    latitude: 44.87
    longitude: 20.64
    name: Pančevo
  pozarevac:
    latitude: 44.62
    longitude: 21.19
    name: Požarevac
  sabac:
    latitude: 44.75
    longitude: 19.69
    name: Šabac
  smederevo:
    latitude: 44.66
    longitude: 20.93
    name: Smederevo
  sremska_mitrovica:
    latitude: 44.98
    longitude: 19.61
    name: Sremska Mitrovica
  sremski_karlovci:
    latitude: 45.2
    longitude: 19.94
    name: Sremski Karlovci
  subotica:
    latitude: 46.1
    longitude: 19.67
    name: Subotica
  valjevo:
    latitude: 44.27
    longitude: 19.89
    name: Valjevo
  vranje:
    latitude: 42.55
    longitude: 21.9
    name: Vranje
  vrbas:
    latitude: 45.57
    longitude: 19.65
    name: Vrbas
  zrenjanin:
    latitude: 45.38
    longitude: 20.38
    name: Zrenjanin
web_interface:
  animation_duration: 500
  default_chart_type: line
  show_grid: true
  theme: light
web_server:
  auto_refresh_interval: 300
  default_host: localhost
  default_port: 8080
  enable_cors: true
  max_data_points: 1000
